---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: foundationalinfrastructure/gce-cpi-release
inputs:
  - name: bosh-cpi-src
  - name: environment
  - name: jq-blob
  - name: aliyun-cli
run:
  path: bosh-cpi-src/ci/tasks/ensure-terminated.sh
params:
  ALICLOUD_ACCESS_KEY_ID:     ""
  ALICLOUD_ACCESS_KEY_SECRET: ""
  ALICLOUD_DEFAULT_REGION:    ""