---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: bosh/integration
    tag: main

inputs:
  - name: bosh-cpi-src
  - name: environment
  - name: stemcell
  - name: bosh-cli
  - name: director-state
  - name: aliyun-cli

run:
  path: bosh-cpi-src/ci/tasks/run-nvme-customer-journey.sh

params:
  ALICLOUD_ACCESS_KEY_ID: ""
  ALICLOUD_SECRET_ACCESS_KEY: ""
  LEGACY_INSTANCE_TYPE: ecs.hfc6.xlarge
  NVME_INSTANCE_TYPE: ecs.c9i.large
