---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: foundationalinfrastructure/gce-cpi-release
inputs:
  - name: bosh-cpi-src

run:
  path: sh
  args:
  - -exc
  - |
    chmod +x bosh-cpi-src/ci/tasks/unit-tests.sh
    bash bosh-cpi-src/ci/tasks/unit-tests.sh

params:
  ALICLOUD_ACCESS_KEY_ID:     ""
  ALICLOUD_ACCESS_KEY_SECRET: ""
  ALICLOUD_DEFAULT_REGION:    ""